version: "3"
services:
  tests:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "tools/wait-for-it.sh db:5432 && R -e 'devtools::check()'"
    working_dir: /app
    links:
      - db
  db:
    build:
      context: db
      dockerfile: Dockerfile
